<?php

namespace AppBundle\Repository;

/**
 * Acta_presidencialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Acta_presidencialRepository extends \Doctrine\ORM\EntityRepository
{
}
