<?php

namespace AppBundle\Repository;

/**
 * JrvRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JrvRepository extends \Doctrine\ORM\EntityRepository
{
}
