<?php

namespace AppBundle\Repository;

/**
 * TransmitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransmitterRepository extends \Doctrine\ORM\EntityRepository
{
}
