<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'service_locator.edmpy9v' shared service.

return $this->services['service_locator.edmpy9v'] = new \Symfony\Component\DependencyInjection\ServiceLocator(['userManager' => function () {
    return ${($_ = isset($this->services['fos_user.user_manager']) ? $this->services['fos_user.user_manager'] : $this->load('getFosUser_UserManagerService.php')) && false ?: '_'};
}]);
