## YAML Template.
---
api_login_check:
    path: /api/login_check
    
api_auth_login:
    path: /api/auth/login
    methods:  [POST]
    
api:
    prefix: /api
    resource: '../src/AppBundle/Controller/Prueba'