<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ32vpto\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ32vpto/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerJ32vpto.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerJ32vpto\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerJ32vpto\appProdProjectContainer([
    'container.build_hash' => 'J32vpto',
    'container.build_id' => 'fdf58783',
    'container.build_time' => 1588194768,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ32vpto');
