<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIj5urym\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIj5urym/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIj5urym.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIj5urym\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIj5urym\appProdProjectContainer([
    'container.build_hash' => 'Ij5urym',
    'container.build_id' => '607f02c5',
    'container.build_time' => 1586909245,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIj5urym');
