<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4zbp8oz\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4zbp8oz/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/Container4zbp8oz.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\Container4zbp8oz\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \Container4zbp8oz\appDevDebugProjectContainer([
    'container.build_hash' => '4zbp8oz',
    'container.build_id' => 'b68e55a6',
    'container.build_time' => 1588194791,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4zbp8oz');
