<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRbeog1f\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRbeog1f/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerRbeog1f.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerRbeog1f\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerRbeog1f\appDevDebugProjectContainer([
    'container.build_hash' => 'Rbeog1f',
    'container.build_id' => 'e63ed0ce',
    'container.build_time' => 1588275812,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRbeog1f');
