<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEm62pqc\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEm62pqc/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerEm62pqc.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerEm62pqc\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerEm62pqc\appDevDebugProjectContainer([
    'container.build_hash' => 'Em62pqc',
    'container.build_id' => 'fe6a4c0b',
    'container.build_time' => 1586909251,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEm62pqc');
