<?php

namespace Proxies\__CG__\AppBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Acta_presidencial extends \AppBundle\Entity\Acta_presidencial implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'fmln', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'ds', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'pdc', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'pcn', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'gana', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'vamos', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'arena', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'coalicion', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'sobrantes', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'escrutados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'inutilizadas', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'faltantes', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'nulo', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'impugnados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'abstenciones', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'entregados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'municipioid', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'useradic', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'fechaadic', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'centrovotacion', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'jrv', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'deviceid'];
        }

        return ['__isInitialized__', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'id', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'fmln', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'ds', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'pdc', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'pcn', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'gana', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'vamos', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'arena', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'coalicion', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'sobrantes', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'escrutados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'inutilizadas', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'faltantes', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'nulo', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'impugnados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'abstenciones', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'entregados', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'municipioid', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'useradic', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'fechaadic', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'centrovotacion', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'jrv', '' . "\0" . 'AppBundle\\Entity\\Acta_presidencial' . "\0" . 'deviceid'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Acta_presidencial $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setFmln($fmln)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFmln', [$fmln]);

        return parent::setFmln($fmln);
    }

    /**
     * {@inheritDoc}
     */
    public function getFmln()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFmln', []);

        return parent::getFmln();
    }

    /**
     * {@inheritDoc}
     */
    public function setDs($ds)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDs', [$ds]);

        return parent::setDs($ds);
    }

    /**
     * {@inheritDoc}
     */
    public function getDs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDs', []);

        return parent::getDs();
    }

    /**
     * {@inheritDoc}
     */
    public function setPdc($pdc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPdc', [$pdc]);

        return parent::setPdc($pdc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPdc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPdc', []);

        return parent::getPdc();
    }

    /**
     * {@inheritDoc}
     */
    public function setPcn($pcn)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPcn', [$pcn]);

        return parent::setPcn($pcn);
    }

    /**
     * {@inheritDoc}
     */
    public function getPcn()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPcn', []);

        return parent::getPcn();
    }

    /**
     * {@inheritDoc}
     */
    public function setGana($gana)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGana', [$gana]);

        return parent::setGana($gana);
    }

    /**
     * {@inheritDoc}
     */
    public function getGana()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGana', []);

        return parent::getGana();
    }

    /**
     * {@inheritDoc}
     */
    public function setVamos($vamos)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVamos', [$vamos]);

        return parent::setVamos($vamos);
    }

    /**
     * {@inheritDoc}
     */
    public function getVamos()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVamos', []);

        return parent::getVamos();
    }

    /**
     * {@inheritDoc}
     */
    public function setArena($arena)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setArena', [$arena]);

        return parent::setArena($arena);
    }

    /**
     * {@inheritDoc}
     */
    public function getArena()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArena', []);

        return parent::getArena();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoalicion($coalicion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoalicion', [$coalicion]);

        return parent::setCoalicion($coalicion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoalicion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoalicion', []);

        return parent::getCoalicion();
    }

    /**
     * {@inheritDoc}
     */
    public function setSobrantes($sobrantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSobrantes', [$sobrantes]);

        return parent::setSobrantes($sobrantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getSobrantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSobrantes', []);

        return parent::getSobrantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setInutilizadas($inutilizadas)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInutilizadas', [$inutilizadas]);

        return parent::setInutilizadas($inutilizadas);
    }

    /**
     * {@inheritDoc}
     */
    public function getInutilizadas()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInutilizadas', []);

        return parent::getInutilizadas();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaltantes($faltantes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaltantes', [$faltantes]);

        return parent::setFaltantes($faltantes);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaltantes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaltantes', []);

        return parent::getFaltantes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNulo($nulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNulo', [$nulo]);

        return parent::setNulo($nulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNulo', []);

        return parent::getNulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setImpugnados($impugnados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImpugnados', [$impugnados]);

        return parent::setImpugnados($impugnados);
    }

    /**
     * {@inheritDoc}
     */
    public function getImpugnados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImpugnados', []);

        return parent::getImpugnados();
    }

    /**
     * {@inheritDoc}
     */
    public function setAbstenciones($abstenciones)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAbstenciones', [$abstenciones]);

        return parent::setAbstenciones($abstenciones);
    }

    /**
     * {@inheritDoc}
     */
    public function getAbstenciones()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAbstenciones', []);

        return parent::getAbstenciones();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntregados($entregados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntregados', [$entregados]);

        return parent::setEntregados($entregados);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntregados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntregados', []);

        return parent::getEntregados();
    }

    /**
     * {@inheritDoc}
     */
    public function setMunicipioid($municipioid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMunicipioid', [$municipioid]);

        return parent::setMunicipioid($municipioid);
    }

    /**
     * {@inheritDoc}
     */
    public function getMunicipioid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMunicipioid', []);

        return parent::getMunicipioid();
    }

    /**
     * {@inheritDoc}
     */
    public function setUseradic($useradic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUseradic', [$useradic]);

        return parent::setUseradic($useradic);
    }

    /**
     * {@inheritDoc}
     */
    public function getUseradic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUseradic', []);

        return parent::getUseradic();
    }

    /**
     * {@inheritDoc}
     */
    public function setFechaadic($fechaadic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFechaadic', [$fechaadic]);

        return parent::setFechaadic($fechaadic);
    }

    /**
     * {@inheritDoc}
     */
    public function getFechaadic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFechaadic', []);

        return parent::getFechaadic();
    }

    /**
     * {@inheritDoc}
     */
    public function setJrv(\AppBundle\Entity\Jrv $jrv)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJrv', [$jrv]);

        return parent::setJrv($jrv);
    }

    /**
     * {@inheritDoc}
     */
    public function getJrv()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJrv', []);

        return parent::getJrv();
    }

    /**
     * {@inheritDoc}
     */
    public function setCentrovotacion($centrovotacion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCentrovotacion', [$centrovotacion]);

        return parent::setCentrovotacion($centrovotacion);
    }

    /**
     * {@inheritDoc}
     */
    public function getCentrovotacion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCentrovotacion', []);

        return parent::getCentrovotacion();
    }

    /**
     * {@inheritDoc}
     */
    public function setEscrutados($escrutados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEscrutados', [$escrutados]);

        return parent::setEscrutados($escrutados);
    }

    /**
     * {@inheritDoc}
     */
    public function getEscrutados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEscrutados', []);

        return parent::getEscrutados();
    }

    /**
     * {@inheritDoc}
     */
    public function setDeviceid($deviceid)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDeviceid', [$deviceid]);

        return parent::setDeviceid($deviceid);
    }

    /**
     * {@inheritDoc}
     */
    public function getDeviceid()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDeviceid', []);

        return parent::getDeviceid();
    }

}
